Header header

std_msgs/Float32MultiArray white1
std_msgs/Float32MultiArray red1
std_msgs/Float32MultiArray green1

std_msgs/Float32MultiArray white2
std_msgs/Float32MultiArray red2
std_msgs/Float32MultiArray green2

---

geometry_msgs/Pose pose
std_msgs/Float64 weight
std_msgs/Int32 num_particles 